services:
  - docker:dind

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull --rm -f "Dockerfile" -t $CI_REGISTRY_IMAGE:latest "." 
    - docker push $CI_REGISTRY_IMAGE:latest